apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BuiThanhNghiaDTU19122004/buithanhnghia-aws-accelerator-p2.git
    path: cloud/w10/lab/rbac
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true