apiVersion: v1
kind: Service
metadata:
  name: game-store
  namespace: demo
  labels:
    app.kubernetes.io/part-of: w10-project
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: game-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30081