apiVersion: v1
kind: Pod
metadata:
  name: test-hostnet
  namespace: demo
spec:
  hostNetwork: true
  containers:
  - name: test-hostnet
    image: ghcr.io/buithanhnghiadtu19122004/api:v3
    resources:
      limits:
        cpu: 100m
        memory: 64Mi