apiVersion: v1
kind: Pod
metadata:
  name: test-root
  namespace: demo
spec:
  containers:
  - name: test-root
    image: ghcr.io/buithanhnghiadtu19122004/api:v3
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 100m
        memory: 64Mi