# Rule 03: Cấm runAsUser: 0 (chạy root)
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockRootUser
metadata:
  name: no-root-user
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: warn
  match:
    kinds:
    - apiGroups: [""]
      kinds:
        - Pod

    - apiGroups: ["apps"]
      kinds:
        - Deployment

    - apiGroups: ["argoproj.io"]
      kinds:
        - Rollout